---
title: "DCS Typhi in Blantyre"
author: "Philip Ashton"
date: "30/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(readxl)
library(broom)
library(lubridate)
```

## Key variables

```{r KeyVariables}
tyvac_pop <- 17695 # ndirande intention to treat population (or should we use the per protocol number?)
strataa_pop <- 102242 # the population size at the final census (aug 2018-April 2019)
```

## Import data

```{r ImportData}

line_list_handle <- "~/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2022.04.08/2022.04.08 line list.xlsx"

all_typhi <- read_excel("~/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2022.04.08/2022.04.08 line list.xlsx", col_types = c("text", "text", "text", 
        "text", "date", "text", "text", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text"))

all_typhi$Month <- as.Date(cut(all_typhi$`Properly formatted date`, breaks = "month"))


```

## Incidence rates

```{r}

tyvac_cases <- all_typhi %>% filter(Study == 'TyVAC' & `TyVAC site` == 'Ndirande' & `Properly formatted date` < '2020-01-01' & !is.na(`Sequenced?`)) %>% filter(!grepl("^Ignore", Note))
tyvac_cases_by_month <- tyvac_cases %>% group_by(Month) %>% summarise(tyvac_n = n())

strataa_cases <- all_typhi %>% filter(grepl('STRATAA', Study) & `Properly formatted date` < '2020-01-01' & !is.na(`Sequenced?`))
strataa_cases_by_month <- strataa_cases  %>% group_by(Month) %>% summarise(strataa_n = n())

#cases_start <- min(strataa_cases_by_month$Month, tyvac_cases_by_month$Month)
#cases_end <- max(strataa_cases_by_month$Month, tyvac_cases_by_month$Month)

# get the official start date of tyvac, as this will determine the start period
combined_cases_by_month <- data.frame(Month = seq(as.Date('2018-05-01'), as.Date('2019-10-01'), "months")) 
#combined_by_month <- combined_by_month %>% rename(V1 = Month)
combined_cases_by_month <- left_join(combined_cases_by_month, tyvac_cases_by_month, by = 'Month')
combined_cases_by_month <- left_join(combined_cases_by_month, strataa_cases_by_month, by = 'Month')
combined_cases_by_month[is.na(combined_cases_by_month)] <- 0

combined_cases_by_month$total_n <- combined_cases_by_month$tyvac_n + combined_cases_by_month$strataa_n
combined_cases_by_month$total_incidence_per100000 <- (combined_cases_by_month$total_n / strataa_pop) * 100000

```

## cipro prescription incidence rates

```{r}

strataa_prescriptions <- read_csv("/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.04.08/2021.04.01 strataa_ndirande_prescribed from James Meiring.csv", 
    col_types = cols(ps12_dov = col_datetime(format = "%d/%m/%Y %H:%M")))

strataa_prescriptions$Month <- as.Date(cut(strataa_prescriptions$ps12_dov, breaks = "month"))
strataa_prescriptions <- strataa_prescriptions %>% filter(ps44_cipro == 1)
strpresc_by_month <- strataa_prescriptions %>% group_by(Month) %>% summarise(n = n())
#ggplot(strataa_prescriptions)
strpresc_by_month$strataa_prescrip_per100000 <- (strpresc_by_month$n / strataa_pop) * 100000

tyvacpresc_by_month <- read_csv("/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.04.08/2021.04.08 cipro prescriptions.csv", col_types = cols(Month = col_date(format = "%d/%m/%Y")))

tyvacpresc_by_month$tyvac_prescrip_eligible_per100000 <- (tyvacpresc_by_month$tyvac_eligible_ciprofloxacin_prescribed / tyvac_pop) * 100000
tyvacpresc_by_month$tyvac_prescrip_not_eligible_per100000 <- (tyvacpresc_by_month$tyvac_not_eligible_ciprofloxacin_prescribed / tyvac_pop) * 100000

prescrip_start <- min(strataa_prescriptions$Month, tyvacpresc_by_month$Month)
prescrip_end <- max(strataa_prescriptions$Month, tyvacpresc_by_month$Month)

combined_prescrip_by_month <- data.frame(Month = seq(prescrip_start, prescrip_end, "months")) 
combined_prescrip_by_month <- left_join(combined_prescrip_by_month, tyvacpresc_by_month, by = 'Month')


```


## Figure 1

This is a figure of the number of S. Typhi at QECH that were cipro sensitive and DCS.

```{r Figure1}

pef_tested_qech_typhi <- all_typhi %>% filter(grepl('QECH', Study)) %>% filter(!is.na(`Cipro MIC res?`))
pef_by_month <- pef_tested_qech_typhi %>% group_by(Month, `Cipro MIC res?`) %>% summarise(n = n())
pef_by_month <- pef_by_month %>% filter(Month >= "2019-01-01")

ggplot(pef_by_month, aes(x = Month, y = n, fill = `Cipro MIC res?`)) + 
  geom_bar(stat = "identity") + 
  ylab("Number of samples") +
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14))

ggplot(pef_by_month, aes(x = Month, y = n, fill = `Cipro MIC res?`, label = n)) + 
  geom_bar(position = 'fill', stat = "identity") + 
  ylab("Number of samples") +
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14))
```

## Numbers for Figure 1

```{r}
total_qech_typhi_tested <- sum(pef_by_month$n)
total_qech_typhi_dcs_or_r <- filter(pef_by_month, `Cipro MIC res?` == 'DCS' | `Cipro MIC res?` == 'R' ) %>% pull(n) %>% sum
```

There were `r total_qech_typhi_tested` total qech typhi tested, and `r total_qech_typhi_dcs_or_r` DCS or R.


## Figure 2

```{r Figure2}

d <- read_csv("/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/epi_analysis/results/2022.06.17/2022.06.17.combined_typhi_data.csv", col_types = cols(Month = col_date(format = "%d/%m/%Y")))

d <- d |>
  mutate(date = ymd(Month)) |>
  arrange(date) |>
  mutate(month_number = row_number()) |>
  mutate(total_cases = no_qrdr + any_qrdr) |>
  rename(`Cipro prescriptions` = `elible_ciprofloxacin prescribed`)

e <- d |>
  dplyr::select(date, `Cipro prescriptions`, no_qrdr, any_qrdr, total_cases) |>
  pivot_longer(-date)

e |>
  ggplot() +
  geom_col(aes(x=date, y=value, fill=name)) +
  facet_grid(name~., scales = "free_y") +
  theme_linedraw() +
  scale_fill_brewer(palette="Set1") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5)) +
  labs(x="Month",
       y="Count") +
  scale_x_date(breaks = scales::breaks_pretty(20)) +
  scale_y_continuous(breaks = scales::breaks_pretty(5))
```








